stages:
  - landing
  - build
  - deploy
landing:
  stage: landing
  image: node:14-alpine
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - cd landing-site
    - npm cache clean -f
    - npm i
    - export NODE_ENV=production
    - export VUE_APP_API=/api/v1/
    - npm run build
    - rsync -ramz --stats --delete ./dist/ $STAGING_HOST:$LANDING_PATH
  only:
    - staging
build:
  stage: build
  image: node:14-alpine
  script:
    - npm cache clean -f
    - npm ci
    - export NODE_ENV=production
    - export VUE_APP_API=/api/v1/
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: '1 hour'
  only:
    - staging
staging_deploy:
  stage: deploy
  image: alpine
  dependencies:
    - build
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -ramz --stats --delete ./dist/ $STAGING_HOST:$STAGING_PATH
  only:
    - staging
